In [3]:
# # 정적 페이지 크롤링
%conda install requests beautifulsoup4 lxml

# # 동적 페이지 크롤링
# %conda install selenium

# ChromeDriver Download
# %conda install webdriver-manager

# # 데이터 처리
# %conda install pandas

3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

In [5]:
import requests
from bs4 import BeautifulSoup

# 1. http 요청
url = 'http://example.com/'
response = requests.get(url)

response.text

# 2. html 파싱
soup = BeautifulSoup(response.text, 'lxml')

# 3. 데이터 추출
title = soup.find('h1').text
print(title)

Example Domain

In [26]:
from bs4 import BeautifulSoup
html = """
<html>
  <head><title>샘플 페이지</title></head>
  <body>
    <h1 class="main-title">제목</h1>
    <div id="content">
      <p class="text">첫 번째 문단</p>
      <p class="text">두 번째 문단</p>
      <a href="/page1">링크1</a>
      <a href="/page2">링크2</a>
    </div>
  </body>
</html>
"""
soup = BeautifulSoup(html, 'lxml')
soup

<html>
<head><title>샘플 페이지</title></head>
<body>
<h1 class="main-title">제목</h1>
<div id="content">
<p class="text">첫 번째 문단</p>
<p class="text">두 번째 문단</p>
<a href="/page1">링크1</a>
<a href="/page2">링크2</a>
</div>
</body>
</html>

### 데이터 찾기 메서드

In [ ]:
# 태그로 찾기
title = soup.find('h1')
print(title.text)

print( soup.find('p') )
print( soup.find_all('p') )

for p in soup.find_all('p'):
    print(p.text)

# CSS 선택자 (select)
# class로 찾기
texts = soup.select('.text')
print(texts)

# id로 찾기
content = soup.select('#content')

# 복합 선택자
links = soup.select('div#content a')

# 태그명으로 찾기
soup.select('p')

제목
<p class="text">첫 번째 문단</p>
[<p class="text">첫 번째 문단</p>, <p class="text">두 번째 문단</p>]
첫 번째 문단
두 번째 문단
[<p class="text">첫 번째 문단</p>, <p class="text">두 번째 문단</p>]

In [38]:
html = """
<html>
  <body>
    <a href="/page1">링크1</a>
    <a href="/page2">링크2</a>
    <img src="/image1.jpg" alt="이미지1">
    <img src="/image2.jpg" alt="이미지2">
  </body>
</html>
"""
# soup = BeautifluSoup(html, 'lxml')
soup = BeautifulSoup(html, 'html.parser')

# href 속성 가져오기
link = soup.find('a')
print( link['href'] )
print( link.get('h') ) # 안전한 방법

# 모든 링크
links = soup.select('a')
print(links)
for i in links:
    print( i.get('href') )
    print(i.text)

/page1
None
[<a href="/page1">링크1</a>, <a href="/page2">링크2</a>]
/page1
링크1
/page2
링크2

In [ ]:
import requests
from bs4 import BeautifulSoup
url = 'https://books.toscrape.com/'
response = requests.get(url)
response.raise_for_status()  # 에러체크

soup = BeautifulSoup(response.text, 'lxml')
soup.select('article.product_pod')[0].select_one('h3 a').get('title')

'A Light in the Attic'

In [65]:
import requests
from bs4 import BeautifulSoup
url = 'https://books.toscrape.com/'
response = requests.get(url)
response.raise_for_status()  # 에러체크
soup = BeautifulSoup(response.text, 'lxml')

titles, links = [], []
for li in soup.select('ol.row li'):
    titles.append( li.select('article.product_pod')[0].select_one('h3 a').get('title') )
    links.append( url + li.select('article.product_pod')[0].select_one('h3 a').get('href') )

In [66]:
import pandas as pd
data = {
    'title' : titles,
    'links' : links
}
pd.DataFrame(data)

,title,links
0,A Light in the Attic,https://books.toscrape.com/catalogue/a-light-i...
1,Tipping the Velvet,https://books.toscrape.com/catalogue/tipping-t...
2,Soumission,https://books.toscrape.com/catalogue/soumissio...
3,Sharp Objects,https://books.toscrape.com/catalogue/sharp-obj...
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/sapiens-a...
5,The Requiem Red,https://books.toscrape.com/catalogue/the-requi...
6,The Dirty Little Secrets of Getting Your Dream...,https://books.toscrape.com/catalogue/the-dirty...
7,The Coming Woman: A Novel Based on the Life of...,https://books.toscrape.com/catalogue/the-comin...
8,The Boys in the Boat: Nine Americans and Their...,https://books.toscrape.com/catalogue/the-boys-...
9,The Black Maria,https://books.toscrape.com/catalogue/the-black...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",https://books.toscrape.com/catalogue/starving-...
11,Shakespeare's Sonnets,https://books.toscrape.com/catalogue/shakespea...
12,Set Me Free,https://books.toscrape.com/catalogue/set-me-fr...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,https://books.toscrape.com/catalogue/scott-pil...
14,Rip it Up and Start Again,https://books.toscrape.com/catalogue/rip-it-up...
15,Our Band Could Be Your Life: Scenes from the A...,https://books.toscrape.com/catalogue/our-band-...
16,Olio,https://books.toscrape.com/catalogue/olio_984/...
17,Mesaerion: The Best Science Fiction Stories 18...,https://books.toscrape.com/catalogue/mesaerion...
18,Libertarianism for Beginners,https://books.toscrape.com/catalogue/libertari...
19,It's Only the Himalayas,https://books.toscrape.com/catalogue/its-only-...

In [3]:
import requests
from bs4 import BeautifulSoup
titles, links = [], []

for pagenum in range(1,11):
    url = f'https://books.toscrape.com/catalogue/page-{pagenum}.html'
    response = requests.get(url)
    response.raise_for_status()  # 에러체크

    soup = BeautifulSoup(response.text, 'lxml')


    for li in soup.select('ol.row li'):
        titles.append( li.select('article.product_pod')[0].select_one('h3 a').get('title') )
        links.append( url + li.select('article.product_pod')[0].select_one('h3 a').get('href') )

In [4]:
import pandas as pd
data = {
    'title' : titles,
    'links' : links
}
pd.DataFrame(data)

,title,links
0,A Light in the Attic,https://books.toscrape.com/catalogue/page-1.ht...
1,Tipping the Velvet,https://books.toscrape.com/catalogue/page-1.ht...
2,Soumission,https://books.toscrape.com/catalogue/page-1.ht...
3,Sharp Objects,https://books.toscrape.com/catalogue/page-1.ht...
4,Sapiens: A Brief History of Humankind,https://books.toscrape.com/catalogue/page-1.ht...
...,...,...
195,Eureka Trivia 6.0,https://books.toscrape.com/catalogue/page-10.h...
196,Drive: The Surprising Truth About What Motivat...,https://books.toscrape.com/catalogue/page-10.h...
197,Done Rubbed Out (Reightman & Bailey #1),https://books.toscrape.com/catalogue/page-10.h...
198,Doing It Over (Most Likely To #1),https://books.toscrape.com/catalogue/page-10.h...
199,Deliciously Ella Every Day: Quick and Easy Rec...,https://books.toscrape.com/catalogue/page-10.h...

In [6]:
import requests
from bs4 import BeautifulSoup
url = 'https://news.naver.com/section/100'

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

result = soup.select_one('div.section_article.as_headline._TEMPLATE')
for data in result.select('ul>li'):
    print(data.select_one('strong.sa_text_strong').text)

김부겸, 대구시장 사실상 출마
'룸살롱 폭행·억대 체납' 이혁재가 심사위원?…국힘 청년 오디션 '시끌'
벨라루스 대통령 첫 방북…김정은, 성대한 환영식으로 '극진 환대'
與김부겸, 국힘 대구시장 후보군 '양자 대결' 모두 우위 [리얼미터]
주호영, 컷오프 정지 가처분 신청…  ‘무소속 출마 명분쌓기’ 해석
李대통령 '축구장 3개 규모' KF-21 고정익 생산현장 시찰…"체계화 확인"
장동혁 지도부, 막말 논란 빚은 박민영 대변인 재임명
조우진-서경덕, '안중근 순국일' 기념해 다국어 영상 제작
이 대통령, 재산 49억 원 신고… 인세·ETF투자로 1년 만에 약 19억 증가
주한이란대사 "이란 내 한국인 대피 적극 협조하겠다"